name: Keep App Awake

on:
  schedule:
    - cron: '0 */6 * * *' # 6時間ごとに自動実行 (1日4回)
  workflow_dispatch: # 手動で実行したい時用のボタンを出す設定

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I "https://strava-maint-kbeijkshzbc9bjh3denedf.streamlit.app/"